import {execFileSync,spawnSync} from 'node:child_process';
import {writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {retitleV9} from './retitle-demo-v9.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),dir=root+'data/film-v9/',out=root+'exports/';await mkdir(out,{recursive:true});
const file=out+'ai-town-demo-v9.mp4';
const measure=spawnSync('ffmpeg',['-hide_banner','-i',dir+'master.wav','-af','loudnorm=I=-16:TP=-1.0:LRA=16:print_format=json','-f','null','-'],{encoding:'utf8'});
if(measure.status!==0)throw new Error('Loudness analysis failed');
const loudness=JSON.parse(measure.stderr.match(/\{[^{}]+\}/s)[0]);
const norm=`loudnorm=I=-16:TP=-1.0:LRA=16:measured_I=${loudness.input_i}:measured_TP=${loudness.input_tp}:measured_LRA=${loudness.input_lra}:measured_thresh=${loudness.input_thresh}:offset=${loudness.target_offset}:linear=true:print_format=json`;
const normalized=spawnSync('ffmpeg',['-y','-hide_banner','-i',dir+'master.wav','-af',norm,'-ar','48000','-ac','2',dir+'master-normalized.wav'],{encoding:'utf8'});
if(normalized.status!==0)throw new Error('Loudness normalization failed');
await writeFile(dir+'loudness.json',JSON.stringify({analysis:loudness,master:JSON.parse(normalized.stderr.match(/\{[^{}]+\}/s)[0])},null,2));
execFileSync('ffmpeg',['-y','-v','error','-i',dir+'picture.mp4','-i',dir+'master-normalized.wav','-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','256k','-ar','48000','-t','60','-movflags','+faststart',dir+'before-title.mp4']);
await retitleV9(dir+'before-title.mp4',file);
console.log('Verified: 60 seconds · 1920×1080 · 30 fps · H.264 + stereo AAC · full decode passed.');console.log(file);
