import {createWorld} from './world.js';import {upgradeCafe} from './cafe-assets.js';import {upgradeMia,expressions} from './mia-visual.js';
const before=new URLSearchParams(location.search).has('before'),world=createWorld(document.getElementById('world'));
world.camera.position.set(-.8,1.68,3.5);world.camera.lookAt(-5.25,2.3,-5.2);world.camera.fov=53;world.camera.updateProjectionMatrix();
const mia=world.npcs.find(n=>n.id==='mia');mia.root.position.set(-3.9,.18,-.25);world.face(mia,world.camera.position);world.npcs.filter(n=>n!==mia).forEach(n=>n.root.visible=false);
let area,visual,t=0,last=performance.now(),frames=[];
try{if(!before){area=await upgradeCafe(world);visual=upgradeMia(mia);}document.getElementById('status').textContent=before?'Before · 元のカフェ':'After · CC0アセット / カフェ1区画';}catch(e){document.getElementById('status').textContent='アセットを読み込めませんでした';throw e;}
const select=document.getElementById('expression');for(const name of expressions){const option=document.createElement('option');option.value=name;option.textContent=name;select.append(option);}select.value='happy';
document.getElementById('wave').onclick=()=>visual?.wave(t);document.getElementById('clean').onclick=()=>document.querySelectorAll('header,footer').forEach(e=>e.hidden=true);addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('header,footer').forEach(e=>e.hidden=false);});
function frame(now){requestAnimationFrame(frame);const dt=now-last;last=now;if(document.hidden)return;t+=Math.min(dt,50)/1000;area?.update(t);visual?.update(t,select.value,true);world.renderer.render(world.scene,world.camera);if(t>3&&dt>0)frames.push(dt);frames=frames.slice(-300);if(frames.length>30){const avg=frames.reduce((a,b)=>a+b)/frames.length,sorted=[...frames].sort((a,b)=>a-b);document.getElementById('metrics').textContent=JSON.stringify({view:before?'before':'after',samples:frames.length,meanFrameMs:+avg.toFixed(2),p95FrameMs:+sorted[Math.floor(sorted.length*.95)].toFixed(2),drawCalls:world.renderer.info.render.calls,triangles:world.renderer.info.render.triangles,geometries:world.renderer.info.memory.geometries,textures:world.renderer.info.memory.textures,pixelRatio:world.renderer.getPixelRatio()},null,2);}}
requestAnimationFrame(frame);
